document.addEventListener("DOMContentLoaded", async()=>{
 const db=mediaLively.supabase,esc=mediaLively.escapeHTML,list=document.getElementById("anime-list"),count=document.getElementById("count"),input=document.getElementById("search"),form=document.getElementById("search-form");
 const r=await db.from("anime").select("id,title,english_title,genre,description,poster_url,season,season_year,view_count").order("view_count",{ascending:false,nullsFirst:false}).order("id",{ascending:true});
 if(r.error){count.textContent="読み込みエラー";list.innerHTML='<div class="status">アニメ情報を取得できませんでした。</div>';return;}
 const all=r.data||[];
 function render(items){count.textContent=`${items.length}作品`;list.innerHTML=items.length?items.map(a=>`<a class="search-result-item" href="${mediaLively.detailURL(a.id)}">${a.poster_url&&mediaLively.safeURL(a.poster_url)?`<img class="result-thumb" src="${esc(mediaLively.safeURL(a.poster_url))}" alt="${esc(a.title)}" loading="lazy">`:`<div class="search-result-number">${esc((a.title||"?").slice(0,1))}</div>`}<div class="search-result-main"><h3>${esc(a.title)}</h3>${a.english_title?`<div class="english-title">${esc(a.english_title)}</div>`:""}<div class="genre-list">${mediaLively.genres(a.genre).slice(0,4).map(g=>`<span class="genre">${esc(g)}</span>`).join("")}</div>${a.description?`<p>${esc(a.description)}</p>`:""}</div><div class="search-arrow">→</div></a>`).join(""):'<div class="status">該当する作品がありません。</div>';}
 function run(q){const k=mediaLively.normalize(q);if(!k){render(all);return;}const scored=all.map(a=>{const fields=[a.title,a.english_title,a.genre,a.description,a.synonyms];let score=0;for(const f of fields){const n=mediaLively.normalize(f);if(n===k)score=Math.max(score,1000);else if(n.startsWith(k))score=Math.max(score,800);else if(n.includes(k))score=Math.max(score,500);}return{a,score};}).filter(x=>x.score).sort((a,b)=>b.score-a.score||mediaLively.normalize(a.a.title).localeCompare(mediaLively.normalize(b.a.title),"ja")).map(x=>x.a);render(scored);}
 input.addEventListener("input",()=>run(input.value));form.addEventListener("submit",e=>{e.preventDefault();run(input.value);history.replaceState(null,"",`anime.html${input.value.trim()?`?q=${encodeURIComponent(input.value.trim())}`:""}`)});const initial=new URLSearchParams(location.search).get("q")||"";input.value=initial;run(initial);
});
