-- Media Lively v5 database extension
-- IMPORTANT: Review and back up the existing Supabase project before executing.
-- Never place a service_role key in front-end code.

begin;

-- Legacy/community compatibility tables
create table if not exists public.anime_likes (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  visitor_id text not null check (char_length(visitor_id) between 8 and 128),
  created_at timestamptz not null default now(),
  unique(anime_id, visitor_id)
);

create table if not exists public.anime_comments (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  visitor_id text not null check (char_length(visitor_id) between 8 and 128),
  nickname text not null check (char_length(nickname) between 1 and 30),
  comment text not null check (char_length(comment) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  company_name text,
  title text,
  description text,
  image_url text,
  link_url text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Anime master fields used by the front-end.
alter table public.anime add column if not exists poster_url text;
alter table public.anime add column if not exists banner_url text;
alter table public.anime add column if not exists title_en text;
alter table public.anime add column if not exists title_romaji text;
alter table public.anime add column if not exists title_kana text;
alter table public.anime add column if not exists type text;
alter table public.anime add column if not exists status text;
alter table public.anime add column if not exists season text;
alter table public.anime add column if not exists season_year integer;
alter table public.anime add column if not exists episodes integer;
alter table public.anime add column if not exists duration_minutes integer;
alter table public.anime add column if not exists source text;
alter table public.anime add column if not exists aired_from date;
alter table public.anime add column if not exists aired_to date;
alter table public.anime add column if not exists age_rating text;
alter table public.anime add column if not exists studios text;
alter table public.anime add column if not exists synopsis_short text;
alter table public.anime add column if not exists synonyms text;
alter table public.anime add column if not exists popularity_count bigint not null default 0;
alter table public.anime add column if not exists view_count bigint not null default 0;
alter table public.anime add column if not exists updated_at timestamptz not null default now();

create table if not exists public.anime_rating_stats (
  anime_id bigint primary key references public.anime(id) on delete cascade,
  rating_count bigint not null default 0,
  average_score numeric(4,2) not null default 0,
  bayesian_score numeric(5,3) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username ~ '^[A-Za-z0-9_]{3,30}$'),
  display_name text,
  bio text check (bio is null or char_length(bio) <= 500),
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.anime_user_list (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  status text not null default 'plan' check(status in ('plan','watching','completed','dropped','paused','rewatching')),
  score numeric(3,1) check(score between 0 and 10),
  progress integer not null default 0 check(progress >= 0),
  is_favorite boolean not null default false,
  notes text check(notes is null or char_length(notes) <= 5000),
  started_at date,
  completed_at date,
  updated_at timestamptz not null default now(),
  primary key(user_id, anime_id)
);

create table if not exists public.anime_follows (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, anime_id)
);

create table if not exists public.anime_reviews (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text check(title is null or char_length(title) <= 150),
  body text not null check(char_length(body) between 1 and 10000),
  score numeric(3,1) not null check(score between 0 and 10),
  spoiler boolean not null default false,
  status text not null default 'published' check(status in ('published','hidden','deleted')),
  helpful_count integer not null default 0,
  comment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_reactions (
  review_id bigint not null references public.anime_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check(reaction in ('helpful','like')),
  created_at timestamptz not null default now(),
  primary key(review_id, user_id, reaction)
);

create table if not exists public.anime_review_comments (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.anime_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.genres (id bigint generated by default as identity primary key, name text unique not null);
create table if not exists public.anime_genres (anime_id bigint not null references public.anime(id) on delete cascade, genre_id bigint not null references public.genres(id) on delete cascade, primary key(anime_id,genre_id));
create table if not exists public.tags (id bigint generated by default as identity primary key, name text unique not null);
create table if not exists public.anime_tags (anime_id bigint not null references public.anime(id) on delete cascade, tag_id bigint not null references public.tags(id) on delete cascade, primary key(anime_id,tag_id));
create table if not exists public.people (id bigint generated by default as identity primary key, name text not null, name_en text, image_url text, biography text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.anime_staff (anime_id bigint not null references public.anime(id) on delete cascade, person_id bigint not null references public.people(id) on delete cascade, role text not null, character_name text, sort_order integer not null default 0, primary key(anime_id,person_id,role,character_name));
create table if not exists public.anime_episodes (id bigint generated by default as identity primary key, anime_id bigint not null references public.anime(id) on delete cascade, episode_number integer not null check(episode_number>0), title text, title_en text, synopsis text, aired_at date, duration_minutes integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(anime_id,episode_number));
create table if not exists public.anime_relations (anime_id bigint not null references public.anime(id) on delete cascade, related_anime_id bigint not null references public.anime(id) on delete cascade, relation_type text not null check(relation_type in ('sequel','prequel','side_story','spin_off','alternative','summary','parent_story','character','other')), sort_order integer not null default 0, primary key(anime_id,related_anime_id,relation_type), check(anime_id<>related_anime_id));
create table if not exists public.anime_external_ids (anime_id bigint primary key references public.anime(id) on delete cascade, mal_id bigint, anilist_id bigint, kitsu_id text, anidb_id text, imdb_id text, official_url text, updated_at timestamptz not null default now());
create table if not exists public.user_follows (follower_id uuid not null references auth.users(id) on delete cascade, following_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(follower_id,following_id), check(follower_id<>following_id));
create table if not exists public.community_posts (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, anime_id bigint references public.anime(id) on delete cascade, post_type text not null check(post_type in ('discussion','analysis','ranking','recommendation')), title text not null check(char_length(title) between 1 and 150), body text not null check(char_length(body) between 1 and 20000), spoiler boolean not null default false, status text not null default 'published' check(status in ('published','hidden','deleted')), like_count integer not null default 0, comment_count integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.anime_views_daily (anime_id bigint not null references public.anime(id) on delete cascade, view_date date not null default current_date, view_count bigint not null default 0, primary key(anime_id,view_date));
create table if not exists public.user_activity (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, anime_id bigint references public.anime(id) on delete cascade, activity_type text not null, created_at timestamptz not null default now());

create index if not exists anime_likes_anime_idx on public.anime_likes(anime_id);
create index if not exists anime_comments_anime_idx on public.anime_comments(anime_id,created_at desc);
create index if not exists anime_season_idx on public.anime(season_year,season);
create index if not exists anime_popularity_idx on public.anime(popularity_count desc);
create index if not exists anime_views_idx on public.anime(view_count desc);
create index if not exists rating_bayes_idx on public.anime_rating_stats(bayesian_score desc);
create index if not exists rating_avg_idx on public.anime_rating_stats(average_score desc);
create index if not exists review_anime_idx on public.anime_reviews(anime_id,created_at desc);
create index if not exists review_score_idx on public.anime_reviews(score desc);
create index if not exists mylist_user_status_idx on public.anime_user_list(user_id,status);
create index if not exists episode_anime_idx on public.anime_episodes(anime_id,episode_number);

-- RLS
alter table public.anime_likes enable row level security;
alter table public.anime_comments enable row level security;
alter table public.advertisements enable row level security;
alter table public.profiles enable row level security;
alter table public.anime_user_list enable row level security;
alter table public.anime_follows enable row level security;
alter table public.anime_reviews enable row level security;
alter table public.review_reactions enable row level security;
alter table public.anime_review_comments enable row level security;
alter table public.genres enable row level security;
alter table public.anime_genres enable row level security;
alter table public.tags enable row level security;
alter table public.anime_tags enable row level security;
alter table public.people enable row level security;
alter table public.anime_staff enable row level security;
alter table public.anime_episodes enable row level security;
alter table public.anime_relations enable row level security;
alter table public.anime_external_ids enable row level security;
alter table public.user_follows enable row level security;
alter table public.community_posts enable row level security;
alter table public.anime_views_daily enable row level security;
alter table public.anime_rating_stats enable row level security;
alter table public.user_activity enable row level security;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin=true); $$;

-- Policies are wrapped so rerunning this file is safe.
do $$ begin create policy "likes public read" on public.anime_likes for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "likes visitor insert" on public.anime_likes for insert with check (char_length(visitor_id) between 8 and 128); exception when duplicate_object then null; end $$;
do $$ begin create policy "likes visitor delete" on public.anime_likes for delete using (char_length(visitor_id) between 8 and 128); exception when duplicate_object then null; end $$;
do $$ begin create policy "comments public read" on public.anime_comments for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "comments visitor insert" on public.anime_comments for insert with check (char_length(visitor_id) between 8 and 128); exception when duplicate_object then null; end $$;
do $$ begin create policy "comments visitor delete" on public.anime_comments for delete using (char_length(visitor_id) between 8 and 128); exception when duplicate_object then null; end $$;
do $$ begin create policy "ads public active read" on public.advertisements for select using (is_active=true or public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "ads admin write" on public.advertisements for all using (public.is_admin_user()) with check (public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "profiles read" on public.profiles for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "profiles own" on public.profiles for all using (auth.uid()=id or public.is_admin_user()) with check (auth.uid()=id or public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "mylist own" on public.anime_user_list for all using (auth.uid()=user_id) with check (auth.uid()=user_id); exception when duplicate_object then null; end $$;
do $$ begin create policy "anime follow own" on public.anime_follows for all using (auth.uid()=user_id) with check (auth.uid()=user_id); exception when duplicate_object then null; end $$;
do $$ begin create policy "reviews published read" on public.anime_reviews for select using (status='published' or auth.uid()=user_id or public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "reviews own" on public.anime_reviews for all using (auth.uid()=user_id or public.is_admin_user()) with check (auth.uid()=user_id or public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "review reaction read" on public.review_reactions for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "review reaction own" on public.review_reactions for all using (auth.uid()=user_id) with check (auth.uid()=user_id); exception when duplicate_object then null; end $$;
do $$ begin create policy "review comments read" on public.anime_review_comments for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "review comments own" on public.anime_review_comments for all using (auth.uid()=user_id) with check (auth.uid()=user_id); exception when duplicate_object then null; end $$;
do $$ begin create policy "catalogue public read" on public.anime_rating_stats for select using (true); create policy "episode public read" on public.anime_episodes for select using (true); create policy "people public read" on public.people for select using (true); create policy "staff public read" on public.anime_staff for select using (true); create policy "genre public read" on public.genres for select using (true); create policy "anime genre public read" on public.anime_genres for select using (true); create policy "tag public read" on public.tags for select using (true); create policy "anime tag public read" on public.anime_tags for select using (true); create policy "relation public read" on public.anime_relations for select using (true); create policy "external public read" on public.anime_external_ids for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "user follows read" on public.user_follows for select using (true); create policy "user follows own" on public.user_follows for all using (auth.uid()=follower_id) with check (auth.uid()=follower_id); exception when duplicate_object then null; end $$;
do $$ begin create policy "community published read" on public.community_posts for select using (status='published' or auth.uid()=user_id or public.is_admin_user()); create policy "community own" on public.community_posts for all using (auth.uid()=user_id or public.is_admin_user()) with check (auth.uid()=user_id or public.is_admin_user()); exception when duplicate_object then null; end $$;
do $$ begin create policy "views admin read" on public.anime_views_daily for select using (public.is_admin_user()); create policy "activity own read" on public.user_activity for select using (auth.uid()=user_id or public.is_admin_user()); exception when duplicate_object then null; end $$;

-- Bayesian ranking refresh. Uses a minimum prior weight of 10 ratings.
create or replace function public.refresh_anime_rating_stats(p_anime_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_count bigint; v_avg numeric(4,2); v_global numeric(4,2); v_bayes numeric(5,3); v_prior numeric:=10;
begin
  select count(*), coalesce(avg(score),0) into v_count,v_avg from public.anime_user_list where anime_id=p_anime_id and score is not null;
  select coalesce(avg(score),0) into v_global from public.anime_user_list where score is not null;
  v_bayes := case when v_count=0 then 0 else ((v_count/(v_count+v_prior))*v_avg)+((v_prior/(v_count+v_prior))*v_global) end;
  insert into public.anime_rating_stats(anime_id,rating_count,average_score,bayesian_score,updated_at) values(p_anime_id,v_count,v_avg,v_bayes,now())
  on conflict(anime_id) do update set rating_count=excluded.rating_count,average_score=excluded.average_score,bayesian_score=excluded.bayesian_score,updated_at=now();
end;
$$;

create or replace function public.refresh_rating_stats_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.refresh_anime_rating_stats(coalesce(new.anime_id,old.anime_id)); return coalesce(new,old); end; $$;
drop trigger if exists trg_refresh_rating_stats on public.anime_user_list;
create trigger trg_refresh_rating_stats after insert or update of score or delete on public.anime_user_list for each row execute function public.refresh_rating_stats_trigger();

create or replace view public.anime_discovery as
select a.id,a.title,coalesce(a.title_en,a.english_title) as title_en,a.title_romaji,a.title_kana,a.genre,a.description,a.type,a.status,a.season,a.season_year,a.episodes,a.poster_url,a.view_count,a.popularity_count,
coalesce(rs.rating_count,0) rating_count,coalesce(rs.average_score,0) average_score,coalesce(rs.bayesian_score,0) bayesian_score
from public.anime a left join public.anime_rating_stats rs on rs.anime_id=a.id;

commit;
