-- メディアライブリー / MAL-scale schema v3
-- Supabase SQL Editorで実行してください。
-- 既存のanime / anime_likes / anime_comments を活かしながら拡張します。

begin;

alter table public.anime add column if not exists poster_url text;
alter table public.anime add column if not exists banner_url text;
alter table public.anime add column if not exists season text;
alter table public.anime add column if not exists season_year integer;
alter table public.anime add column if not exists episodes integer;
alter table public.anime add column if not exists type text;
alter table public.anime add column if not exists studios text;
alter table public.anime add column if not exists source text;
alter table public.anime add column if not exists aired_from date;
alter table public.anime add column if not exists aired_to date;
alter table public.anime add column if not exists duration_minutes integer;
alter table public.anime add column if not exists status text;
alter table public.anime add column if not exists synonyms text;
alter table public.anime add column if not exists age_rating text;
alter table public.anime add column if not exists popularity_count bigint not null default 0;
alter table public.anime add column if not exists view_count bigint not null default 0;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  bio text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.anime_user_list (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  status text not null default 'plan' check(status in ('plan','watching','completed','dropped','paused','rewatching')),
  score numeric(3,1) check(score >= 0 and score <= 10),
  progress integer not null default 0 check(progress >= 0),
  is_favorite boolean not null default false,
  notes text,
  started_at date,
  completed_at date,
  updated_at timestamptz not null default now(),
  primary key(user_id, anime_id)
);

create table if not exists public.anime_reviews (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  body text not null check(char_length(body) between 1 and 10000),
  score numeric(3,1) not null check(score >= 0 and score <= 10),
  spoiler boolean not null default false,
  helpful_count integer not null default 0,
  comment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_reactions (
  review_id bigint not null references public.anime_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null default 'helpful' check(reaction in ('helpful','like')),
  created_at timestamptz not null default now(),
  primary key(review_id,user_id,reaction)
);

create table if not exists public.anime_review_comments (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.anime_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.anime_follows (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,anime_id)
);

create table if not exists public.anime_relations (
  anime_id bigint not null references public.anime(id) on delete cascade,
  related_anime_id bigint not null references public.anime(id) on delete cascade,
  relation_type text not null check(relation_type in ('sequel','prequel','side_story','alternative','spin_off','summary','parent_story','character','other')),
  sort_order integer not null default 0,
  primary key(anime_id,related_anime_id,relation_type),
  check(anime_id <> related_anime_id)
);

create table if not exists public.anime_external_ids (
  anime_id bigint primary key references public.anime(id) on delete cascade,
  mal_id bigint,
  anilist_id bigint,
  kitsu_id text,
  anidb_id text,
  official_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.anime_staff (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  person_name text not null,
  role text not null,
  sort_order integer not null default 0
);

create table if not exists public.anime_tags (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  tag text not null,
  unique(anime_id,tag)
);

create table if not exists public.anime_episodes (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  episode_number integer not null,
  title text,
  aired_at date,
  duration_minutes integer,
  synopsis text,
  unique(anime_id,episode_number)
);

create index if not exists anime_season_idx on public.anime(season_year,season);
create index if not exists anime_type_idx on public.anime(type);
create index if not exists anime_status_idx on public.anime(status);
create index if not exists anime_popularity_idx on public.anime(popularity_count desc);
create index if not exists anime_views_idx on public.anime(view_count desc);
create index if not exists anime_reviews_anime_idx on public.anime_reviews(anime_id,created_at desc);
create index if not exists anime_reviews_score_idx on public.anime_reviews(score desc);
create index if not exists anime_user_list_status_idx on public.anime_user_list(user_id,status);
create index if not exists anime_user_list_score_idx on public.anime_user_list(anime_id,score);
create index if not exists anime_relations_anime_idx on public.anime_relations(anime_id,sort_order);
create index if not exists anime_staff_anime_idx on public.anime_staff(anime_id,sort_order);
create index if not exists anime_tags_anime_idx on public.anime_tags(anime_id);
create index if not exists anime_episodes_anime_idx on public.anime_episodes(anime_id,episode_number);

alter table public.profiles enable row level security;
alter table public.anime_user_list enable row level security;
alter table public.anime_reviews enable row level security;
alter table public.review_reactions enable row level security;
alter table public.anime_review_comments enable row level security;
alter table public.anime_follows enable row level security;
alter table public.anime_relations enable row level security;
alter table public.anime_external_ids enable row level security;
alter table public.anime_staff enable row level security;
alter table public.anime_tags enable row level security;
alter table public.anime_episodes enable row level security;

-- 再実行時の衝突を避けるため、この拡張SQLでは既存ポリシーの削除を行わない。
-- Supabase Dashboardで同名ポリシーが既にある場合は、そのポリシーを整理してから実行してください。

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles public read') then
    create policy "profiles public read" on public.profiles for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles own insert') then
    create policy "profiles own insert" on public.profiles for insert with check (auth.uid() = id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles own update') then
    create policy "profiles own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='anime_user_list' and policyname='mylist own read') then
    create policy "mylist own read" on public.anime_user_list for select using (auth.uid() = user_id);
    create policy "mylist own insert" on public.anime_user_list for insert with check (auth.uid() = user_id);
    create policy "mylist own update" on public.anime_user_list for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
    create policy "mylist own delete" on public.anime_user_list for delete using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='anime_reviews' and policyname='reviews public read') then
    create policy "reviews public read" on public.anime_reviews for select using (true);
    create policy "reviews own insert" on public.anime_reviews for insert with check (auth.uid() = user_id);
    create policy "reviews own update" on public.anime_reviews for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
    create policy "reviews own delete" on public.anime_reviews for delete using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='review_reactions' and policyname='review reactions public read') then
    create policy "review reactions public read" on public.review_reactions for select using (true);
    create policy "review reactions own write" on public.review_reactions for insert with check (auth.uid() = user_id);
    create policy "review reactions own delete" on public.review_reactions for delete using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='anime_review_comments' and policyname='review comments public read') then
    create policy "review comments public read" on public.anime_review_comments for select using (true);
    create policy "review comments own insert" on public.anime_review_comments for insert with check (auth.uid() = user_id);
    create policy "review comments own delete" on public.anime_review_comments for delete using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='anime_follows' and policyname='anime follows own read') then
    create policy "anime follows own read" on public.anime_follows for select using (auth.uid() = user_id);
    create policy "anime follows own insert" on public.anime_follows for insert with check (auth.uid() = user_id);
    create policy "anime follows own delete" on public.anime_follows for delete using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='anime_relations' and policyname='anime relations public read') then
    create policy "anime relations public read" on public.anime_relations for select using (true);
    create policy "anime external ids public read" on public.anime_external_ids for select using (true);
    create policy "anime staff public read" on public.anime_staff for select using (true);
    create policy "anime tags public read" on public.anime_tags for select using (true);
    create policy "anime episodes public read" on public.anime_episodes for select using (true);
  end if;
end $$;

-- 管理者判定用関数。クライアントからservice_roleを扱わない。
create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

-- 評価スコア。評価数の少ない作品が偶然上位に来ることを抑えるためのベイズ平均。
create or replace view public.anime_rating_stats as
select
  a.id as anime_id,
  coalesce(count(ul.score) filter (where ul.score is not null),0)::bigint as rating_count,
  coalesce(avg(ul.score) filter (where ul.score is not null),0)::numeric(4,2) as average_score
from public.anime a
left join public.anime_user_list ul on ul.anime_id = a.id
group by a.id;

commit;
